# Generated by Django 3.2.16 on 2022-12-03 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mengelola_sarana_olahraga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Vacant'), (0, 'Ordered')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal_Reservasi',
            fields=[
                ('id_jadwal', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(default=1, max_length=9)),
                ('datetime', models.DateField(default=datetime.datetime(2022, 12, 3, 6, 52, 18, 228130, tzinfo=utc))),
                ('id_sarana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mengelola_sarana_olahraga.sarana')),
            ],
        ),
    ]
