# Generated by Django 3.2.16 on 2022-12-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mengelola_sarana_olahraga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSewaSarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Menunggu pembayaran'), (1, 'Berhasil dibayar'), (2, 'Batal'), (3, 'Selesai')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SewaSarana',
            fields=[
                ('ID_sewa', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default=0)),
                ('jam_booking', models.JSONField()),
                ('sarana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mengelola_sarana_olahraga.sarana')),
            ],
        ),
    ]
