# Generated by Django 3.2.16 on 2022-12-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('melihat_jadwal_reservasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOR',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('url_foto', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('url_foto', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('Lapangan Basket', 'Lapangan Basket'), ('Lapangan Bulutangkis', 'Lapangan Bulu Tangkis'), ('Lapangan Futsal', 'Lapangan Futsal'), ('Kolam Renang', 'Kolam Renang'), ('Lapangan Sepak Bola', 'Lapangan Sepak Bola')], max_length=200)),
                ('deskripsi', models.TextField()),
                ('gor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mengelola_sarana_olahraga.gor')),
                ('jadwal_reservasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melihat_jadwal_reservasi.jadwalreservasi')),
            ],
        ),
    ]
