# Generated by Django 3.2.16 on 2022-12-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GOR',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('url_foto', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url_foto', models.CharField(max_length=200)),
                ('jenis', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('id_gor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mengelola_sarana_olahraga.gor')),
            ],
        ),
    ]
