# Generated by Django 3.2.16 on 2022-11-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOR',
            fields=[
                ('ID_gor', models.TextField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('url_foto', models.TextField()),
                ('alamat', models.TextField()),
                ('no_telepon', models.TextField()),
                ('pengurus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.pengurus_gor')),
            ],
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('ID_sarana', models.TextField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('url_foto', models.TextField()),
                ('jenis', models.TextField()),
                ('deskripsi', models.TextField()),
                ('gor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sarana_olahraga.gor')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal_Reservasi',
            fields=[
                ('ID_jadwal', models.TextField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('sarana', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sarana_olahraga.sarana')),
            ],
        ),
    ]
