# Generated by Django 3.2.16 on 2022-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_olahraga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal_reservasi',
            name='hari_buka',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='jadwal_reservasi',
            name='jam_buka',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='jadwal_reservasi',
            name='status_book',
            field=models.JSONField(null=True),
        ),
    ]
