# Generated by Django 3.2.16 on 2022-12-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_olahraga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('ID_sarana', models.TextField(primary_key=True, serialize=False)),
                ('id_jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sarana_olahraga.jadwal_reservasi')),
            ],
        ),
    ]
