# Generated by Django 3.2.16 on 2022-12-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana_olahraga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarana',
            name='biaya',
            field=models.FloatField(default=0),
        ),
    ]
