# Generated by Django 3.2.16 on 2022-11-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField()),
                ('confirm_password', models.TextField()),
                ('nama', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nomor_telepon', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Konsumen_GOR',
            fields=[
                ('pengguna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pengguna.pengguna')),
                ('status_loyalty', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('pengguna.pengguna',),
        ),
        migrations.CreateModel(
            name='Pengurus_GOR',
            fields=[
                ('pengguna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pengguna.pengguna')),
                ('akun_bank', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('pengguna.pengguna',),
        ),
    ]
