# Generated by Django 3.2.16 on 2022-11-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sewa_Sarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_sewa', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('biaya', models.FloatField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.TextField()),
                ('bukti_pembayaran', models.TextField()),
                ('sewa_sarana', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sewa.sewa_sarana')),
            ],
        ),
    ]
