# Generated by Django 3.2.16 on 2022-11-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembatalan_Sewa_Sarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_pembatalan', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('sewa_sarana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa.sewa_sarana')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi_Pembatalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.TextField()),
                ('pembatalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa.pembatalan_sewa_sarana')),
            ],
        ),
    ]
