# Generated by Django 3.2.16 on 2022-12-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sewa_Sarana',
            fields=[
                ('ID_sewa', models.TextField(primary_key=True, serialize=False)),
                ('konsumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.konsumen_gor')),
                ('pengurus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.pengurus_gor')),
            ],
        ),
    ]
