# Generated by Django 3.2.16 on 2022-11-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sarana_olahraga', '0001_initial'),
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembatalan_Sewa_Sarana',
            fields=[
                ('ID_pembatalan', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('pembatal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.konsumen_gor')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi_Pembatalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.TextField()),
                ('pembatalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservasi_sarana.pembatalan_sewa_sarana')),
                ('pengurus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.pengurus_gor')),
            ],
        ),
        migrations.CreateModel(
            name='Sewa_Sarana',
            fields=[
                ('ID_sewa', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('biaya', models.FloatField()),
                ('status', models.TextField()),
                ('konsumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.konsumen_gor')),
                ('pengurus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.pengurus_gor')),
                ('sarana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sarana_olahraga.sarana')),
            ],
        ),
        migrations.AddField(
            model_name='pembatalan_sewa_sarana',
            name='sewa_sarana',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservasi_sarana.sewa_sarana'),
        ),
        migrations.CreateModel(
            name='Detail_Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.TextField()),
                ('bukti_pembayaran', models.TextField()),
                ('sewa_sarana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservasi_sarana.sewa_sarana')),
            ],
        ),
    ]
