# Generated by Django 3.2.16 on 2022-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_sarana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_pembayaran',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
