# Generated by Django 3.2.16 on 2022-12-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_sarana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Detail_Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Belum upload bukti pembayaran'), (1, 'Menunggu verifikasi bukti pembayaran'), (2, 'Pembayaran terverifikasi')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Sewa_Sarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Menunggu pembayaran'), (1, 'Berhasil dibayar'), (2, 'Batal'), (3, 'Selesai')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Verifikasi_Pembatalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pembatalan diajukan'), (1, 'Pembatalan terverifikasi')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='detail_pembayaran',
            name='status',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='sewa_sarana',
            name='status',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='verifikasi_pembatalan',
            name='status',
            field=models.TextField(default=0),
        ),
    ]
