# Generated by Django 3.2.16 on 2022-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_sarana', '0002_auto_20221201_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_pembayaran',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
