# Generated by Django 3.2.16 on 2022-12-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_sarana', '0003_alter_detail_pembayaran_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_pembayaran',
            name='bukti_pembayaran',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail_pembayaran',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
