# Generated by Django 3.2.16 on 2022-12-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GOR',
            fields=[
                ('ID_gor', models.TextField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('url_foto', models.TextField()),
                ('alamat', models.TextField()),
                ('no_telepon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('nomor_telepon', models.TextField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sarana',
            fields=[
                ('ID_sarana', models.TextField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('url_foto', models.TextField()),
                ('jenis', models.TextField()),
                ('deskripsi', models.TextField()),
                ('gor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.gor')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Detail_Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Belum upload bukti pembayaran'), (1, 'Menunggu verifikasi bukti pembayaran'), (2, 'Pembayaran terverifikasi')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Sewa_Sarana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Menunggu pembayaran'), (1, 'Berhasil dibayar'), (2, 'Batal'), (3, 'Selesai')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Verifikasi_Pembatalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pembatalan diajukan'), (1, 'Pembatalan terverifikasi')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Konsumen_GOR',
            fields=[
                ('pengguna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testmodels.pengguna')),
                ('status_loyalty', models.TextField()),
            ],
            bases=('testmodels.pengguna',),
        ),
        migrations.CreateModel(
            name='Pengurus_GOR',
            fields=[
                ('pengguna_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testmodels.pengguna')),
                ('akun_bank', models.TextField()),
            ],
            bases=('testmodels.pengguna',),
        ),
        migrations.CreateModel(
            name='Sewa_Sarana',
            fields=[
                ('ID_sewa', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('biaya', models.FloatField(default=0)),
                ('status', models.TextField(default=0)),
                ('sarana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.sarana')),
                ('konsumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.konsumen_gor')),
                ('pengurus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.pengurus_gor')),
            ],
        ),
        migrations.CreateModel(
            name='Pembatalan_Sewa_Sarana',
            fields=[
                ('ID_pembatalan', models.TextField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('pembatal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.pengguna')),
                ('sewa_sarana', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.sewa_sarana')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal_Reservasi',
            fields=[
                ('ID_jadwal', models.TextField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('sarana', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.sarana')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default=0)),
                ('bukti_pembayaran', models.TextField(blank=True, null=True)),
                ('sewa_sarana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.sewa_sarana')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi_Pembatalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default=0)),
                ('pembatalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.pembatalan_sewa_sarana')),
                ('pengurus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.pengurus_gor')),
            ],
        ),
        migrations.AddField(
            model_name='gor',
            name='pengurus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.pengurus_gor'),
        ),
    ]
